-- MySQL Script generated by MySQL Workbench
-- Mon Apr  3 20:31:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dashboard_db
-- -----------------------------------------------------
DROP DATABASE `dashboard_db`;

-- -----------------------------------------------------
-- Schema dashboard_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dashboard_db` DEFAULT CHARACTER SET utf8 ;
USE `dashboard_db` ;

-- -----------------------------------------------------
-- Table `dashboard_db`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_db`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL UNIQUE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dashboard_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_db`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL UNIQUE,
  `senha` VARCHAR(45) NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `dashboard_db`.`perfil` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dashboard_db`.`projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_db`.`projeto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `nome_curto` VARCHAR(45) NULL UNIQUE,
  `descricao` TEXT NULL,
  `status` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  `data_estimada` DATE NULL,
  `percentual` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projeto_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dashboard_db`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dashboard_db`.`usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_db`.`usuario_permissao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permissao` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `projeto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_permissao_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_usuario_permissao_projeto1_idx` (`projeto_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_permissao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `dashboard_db`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_permissao_projeto1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `dashboard_db`.`projeto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dashboard_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_db`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `projeto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_projeto1_idx` (`projeto_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_projeto1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `dashboard_db`.`projeto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dashboard_db`.`funcionalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dashboard_db`.`funcionalidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `nome_curto` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `estimativa_conclusao` DATE NULL,
  `percentual_conclusao` DECIMAL(8,2) NULL,
  `status` VARCHAR(45) NULL,
  `fase` VARCHAR(45) NULL,
  `categoria_id` INT NOT NULL,
  `projeto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionalidade_categoria1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_funcionalidade_projeto1_idx` (`projeto_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionalidade_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `dashboard_db`.`categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_funcionalidade_projeto1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `dashboard_db`.`projeto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE USER IF NOT EXISTS 'dashboard_user'@'localhost' IDENTIFIED BY 'DashPass@2023';
GRANT ALL PRIVILEGES ON dashboard_db.* TO 'dashboard_user'@'localhost';

INSERT INTO `dashboard_db`.`perfil` VALUES (1, 'Admin');
INSERT INTO `dashboard_db`.`perfil` VALUES (2, 'Convidado');
INSERT INTO `dashboard_db`.`perfil` VALUES (3, 'Product Owner');
INSERT INTO `dashboard_db`.`usuario` VALUES (1, 'Admin', 'Dashboard', 'admin@dashboard', 'a47332284f7642643ede76310c05f82a', 1); -- MD5hash of password 'dashadmin'

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
